/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jmZRWx7iGXQ63kqiJRikGa

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsikD9E2PAKbf } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ikD_9E2pAKbf/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsikD9E2PAKbf
});
