/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jmZRWx7iGXQ63kqiJRikGa

import {
  createStyleTokensProvider,
  createUseStyleTokens
} from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jmZRWx7iGXQ63kqiJRikGa/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: jmZRWx7iGXQ63kqiJRikGa/projectcss

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss

const data = {
  base: `${projectcss.plasmic_tokens} ${plasmic_library_plasmic_color_type_css.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  data,
  _useGlobalVariants
);
